In [42]:
import pandas as pd

import numpy as np

# 1. Loading the Data Set

In [3]:
df = pd.read_csv("healthcare_dataset.csv")

df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

# 2. Understanding the Dataset

In [10]:
print(df.head().to_string())

            Name  Age  Gender Blood Type Medical Condition Date of Admission            Doctor                    Hospital Insurance Provider  Billing Amount  Room Number Admission Type Discharge Date   Medication  Test Results
0  Bobby JacksOn   30    Male         B-            Cancer        2024-01-31     Matthew Smith             Sons and Miller         Blue Cross    18856.281306          328         Urgent     2024-02-02  Paracetamol        Normal
1   LesLie TErRy   62    Male         A+           Obesity        2019-08-20   Samantha Davies                     Kim Inc           Medicare    33643.327287          265      Emergency     2019-08-26    Ibuprofen  Inconclusive
2    DaNnY sMitH   76  Female         A-           Obesity        2022-09-22  Tiffany Mitchell                    Cook PLC              Aetna    27955.096079          205      Emergency     2022-10-07      Aspirin        Normal
3   andrEw waTtS   28  Female         O+          Diabetes        2020-11-18       Kevin Wells  Hernandez Rogers and Vang,           Medicare    37909.782410          450       Elective     2020-12-18    Ibuprofen      Abnormal
4  adrIENNE bEll   43  Female        AB+            Cancer        2022-09-19    Kathleen Hanna                 White-White              Aetna    14238.317814          458         Urgent     2022-10-09   Penicillin      Abnormal

In [8]:
describe = df.describe()

describe

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

# 3. Checking Duplicates & Null Values

In [ ]:
print(df.duplicated().sum()) # 534 Duplicate Rows 

print(df.isna().sum()) # 0 null values in the data set

534
Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

# 4. Dropping the Duplicates

In [ ]:
df = df.drop_duplicates()

In [ ]:
df = df.reset_index(drop = True) # Reset the Index

In [ ]:
print(df.duplicated().sum()) # there are 0 duplicate Rows in the Dataset

0

In [10]:
print(f"Cleaned Row Count: {len(df)}")

Cleaned Row Count: 54966

# 5. Standardization

In [13]:
print(df.sample(10).to_string())

                   Name  Age  Gender Blood Type Medical Condition Date of Admission           Doctor                         Hospital Insurance Provider  Billing Amount  Room Number Admission Type Discharge Date   Medication  Test Results
26423     suSAN FreEMaN   56    Male        AB+           Obesity        2019-10-20     Daniel Jones                         Shaw Ltd           Medicare    26689.909282          200       Elective     2019-11-05      Lipitor  Inconclusive
34409      rOBert ayALa   44    Male        AB-      Hypertension        2021-09-30      Nancy Smith     Alexander Patton, Lowery and              Aetna    39252.176546          142         Urgent     2021-10-13      Aspirin  Inconclusive
13719      sARah fishEr   69  Female         A+      Hypertension        2021-01-18      Eric Massey         and Wilson, Wright Moore              Aetna    19369.825313          258       Elective     2021-02-02    Ibuprofen        Normal
18520        aLEXA WarD   35  Female        AB+      Hypertension        2023-01-22  Jessica Russell                     Group Chavez           Medicare     2507.353574          425      Emergency     2023-01-28      Aspirin        Normal
21524       julIE beARD   77  Female        AB+            Cancer        2020-06-11   Ashley Schmidt     and Peterson, Taylor Bridges              Cigna     8946.712555          222         Urgent     2020-06-18   Penicillin        Normal
33269      jaMES WAltOn   33  Female         O+          Diabetes        2022-11-30     Jamie Powell    Foster and Jefferson, Herring              Aetna     9773.210535          219       Elective     2022-12-12  Paracetamol        Normal
3558        tINa MoNTeS   26  Female        AB-            Cancer        2022-05-17  Allison Jackson    Ward and Christensen, Russell   UnitedHealthcare     8308.032812          329      Emergency     2022-06-10   Penicillin  Inconclusive
3595     luCAs SChwARtz   43  Female         A-           Obesity        2022-10-01     Leah Simmons  and Davis Blankenship Mcdowell,           Medicare    38082.474571          264      Emergency     2022-10-12      Lipitor  Inconclusive
12147        jaSoN cOle   84    Male         A-         Arthritis        2023-04-05     Julia Rogers                 Rosales-Gonzalez         Blue Cross    35082.700435          429       Elective     2023-04-08   Penicillin  Inconclusive
14711  JACOB rICHaRdSon   19    Male         O-         Arthritis        2024-04-13     Sean Johnson       and Young, Carpenter Henry              Aetna    45396.088549          295         Urgent     2024-05-12  Paracetamol        Normal

In [ ]:
df["Name"] = df["Name"].str.strip().str.title() # Now the Values ie Rows in Column "Name" looks standardized

In [17]:
df["Doctor"] = df["Doctor"].str.strip().str.title()

In [18]:
df["Hospital"] = df["Hospital"].str.strip()

### Decimal Value Handling

In [ ]:
df["Billing Amount"] = df["Billing Amount"].round(2) # Keeps only 2 Digits after the Decimal

In [25]:
print(df.head().to_string())

            Name  Age  Gender Blood Type Medical Condition Date of Admission            Doctor                    Hospital Insurance Provider  Billing Amount  Room Number Admission Type Discharge Date   Medication  Test Results
0  Bobby Jackson   30    Male         B-            Cancer        2024-01-31     Matthew Smith             Sons and Miller         Blue Cross        18856.28          328         Urgent     2024-02-02  Paracetamol        Normal
1   Leslie Terry   62    Male         A+           Obesity        2019-08-20   Samantha Davies                     Kim Inc           Medicare        33643.33          265      Emergency     2019-08-26    Ibuprofen  Inconclusive
2    Danny Smith   76  Female         A-           Obesity        2022-09-22  Tiffany Mitchell                    Cook PLC              Aetna        27955.10          205      Emergency     2022-10-07      Aspirin        Normal
3   Andrew Watts   28  Female         O+          Diabetes        2020-11-18       Kevin Wells  Hernandez Rogers and Vang,           Medicare        37909.78          450       Elective     2020-12-18    Ibuprofen      Abnormal
4  Adrienne Bell   43  Female        AB+            Cancer        2022-09-19    Kathleen Hanna                 White-White              Aetna        14238.32          458         Urgent     2022-10-09   Penicillin      Abnormal

# 6. Date & Time Column Handling

In [27]:
print(df["Discharge Date"].dtype) # Its is String Data type we need to Convert it into datetime datatype

print(df["Date of Admission"].dtype)

str
str

In [28]:
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])

In [ ]:
print(df["Discharge Date"].dtype) # datetime64[us]

print(df["Date of Admission"].dtype) # datetime64[us]

datetime64[us]
datetime64[us]

In [ ]:
df.dtypes # Looks Better than before

Name                             str
Age                            int64
Gender                           str
Blood Type                       str
Medical Condition                str
Date of Admission     datetime64[us]
Doctor                           str
Hospital                         str
Insurance Provider               str
Billing Amount               float64
Room Number                    int64
Admission Type                   str
Discharge Date        datetime64[us]
Medication                       str
Test Results                     str
dtype: object

# 7. Standardizing the Columns Name

In [32]:
df.columns = df.columns.str.replace(" ", "_")

print(df.columns)

Index(['Name', 'Age', 'Gender', 'Blood_Type', 'Medical_Condition',
       'Date_of_Admission', 'Doctor', 'Hospital', 'Insurance_Provider',
       'Billing_Amount', 'Room_Number', 'Admission_Type', 'Discharge_Date',
       'Medication', 'Test_Results'],
      dtype='str')

# 8. Feature Engineering

####   1. Creating a New Columns that answers the Question "How many Days did the patient Stay"

In [ ]:
df["Lenght_of_Stay"] = (df["Discharge_Date"] - df["Date_of_Admission"]).dt.days

In [55]:
df =df.rename(columns={
    "Lenght_of_Stay" : "Days_Stayed"
})

In [40]:
df.describe()

,Age,Date_of_Admission,Billing_Amount,Room_Number,Discharge_Date,Lenght_of_Stay
count,54966.000000,54966,54966.000000,54966.000000,54966,54966.000000
mean,51.535185,2021-11-01 17:35:29.505512,25544.306260,301.124404,2021-11-17 05:34:28.202161,15.499290
min,13.000000,2019-05-08 00:00:00,-2008.490000,101.000000,2019-05-09 00:00:00,1.000000
25%,35.000000,2020-07-28 00:00:00,13243.722500,202.000000,2020-08-13 00:00:00,8.000000
50%,52.000000,2021-11-02 00:00:00,25542.750000,302.000000,2021-11-18 00:00:00,15.000000
75%,68.000000,2023-02-03 00:00:00,37819.857500,401.000000,2023-02-19 00:00:00,23.000000
max,89.000000,2024-05-07 00:00:00,52764.280000,500.000000,2024-06-06 00:00:00,30.000000
std,19.605661,NaN,14208.409715,115.223143,NaN,8.661471

#### 2. Creating a new Flag Column based on the Column "Billing_Amount"

In [43]:

conditions = [

    df["Billing_Amount"] > 30000,
    (df["Billing_Amount"] > 10000) & (df["Billing_Amount"] < 30000),
    df["Billing_Amount"] < 10000
]

choices = ["High Fees", "Medium Fees", "Low Fees"]

df["Billing_Category"] = np.select(conditions, choices, default="Unknown")

In [44]:
df["Billing_Category"]

0        Medium Fees
1          High Fees
2        Medium Fees
3          High Fees
4        Medium Fees
            ...
54961       Low Fees
54962      High Fees
54963    Medium Fees
54964      High Fees
54965       Low Fees
Name: Billing_Category, Length: 54966, dtype: str

In [45]:
unknown = df[df["Billing_Category"] == "Unknown"]

unknown

Empty DataFrame
Columns: [Name, Age, Gender, Blood_Type, Medical_Condition, Date_of_Admission, Doctor, Hospital, Insurance_Provider, Billing_Amount, Room_Number, Admission_Type, Discharge_Date, Medication, Test_Results, Lenght_of_Stay, Billing_Category]
Index: []

#### 3. Creating a New "Age_Category" column based on Column "Age"

In [52]:
age_conditions = [

    df["Age"] < 18,
    (df["Age"] >= 18) & (df["Age"] <= 35),
    (df["Age"] >= 36) & (df["Age"] <= 50),
    (df['Age'] >= 51) & (df['Age'] <= 65),
    df['Age'] > 65   
]

age_choices = ['Pediatric',
    'Young Adult',
    'Middle-Aged Adult',
    'Pre-Senior',
    'Geriatric']


df["Age_Category"] = np.select(age_conditions, age_choices, default="n/a")

In [53]:
df["Age_Category"]

0              Young Adult
1               Pre-Senior
2                Geriatric
3              Young Adult
4        Middle-Aged Adult
               ...
54961    Middle-Aged Adult
54962           Pre-Senior
54963    Middle-Aged Adult
54964    Middle-Aged Adult
54965           Pre-Senior
Name: Age_Category, Length: 54966, dtype: str

In [56]:
df

,Name,Age,Gender,Blood_Type,Medical_Condition,Date_of_Admission,Doctor,Hospital,Insurance_Provider,Billing_Amount,Room_Number,Admission_Type,Discharge_Date,Medication,Test_Results,Days_Stayed,Billing_Category,Age_Category
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28,328,Urgent,2024-02-02,Paracetamol,Normal,2,Medium Fees,Young Adult
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.33,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6,High Fees,Pre-Senior
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.10,205,Emergency,2022-10-07,Aspirin,Normal,15,Medium Fees,Geriatric
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.78,450,Elective,2020-12-18,Ibuprofen,Abnormal,30,High Fees,Young Adult
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.32,458,Urgent,2022-10-09,Penicillin,Abnormal,20,Medium Fees,Middle-Aged Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54961,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.71,417,Elective,2020-09-15,Penicillin,Abnormal,30,Low Fees,Middle-Aged Adult
54962,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.80,316,Elective,2020-02-01,Aspirin,Normal,9,High Fees,Pre-Senior
54963,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs Dvm,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.76,347,Urgent,2020-08-10,Ibuprofen,Abnormal,28,Medium Fees,Middle-Aged Adult
54964,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.09,321,Elective,2019-05-31,Ibuprofen,Abnormal,6,High Fees,Middle-Aged Adult
54965,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.13,448,Urgent,2024-04-29,Ibuprofen,Abnormal,27,Low Fees,Pre-Senior

# 9. Exporting the File

In [57]:
df.to_csv("healthcare_cleaned.csv", index=False)